  WORKSPACENAME: yd-mlops-dev-123
  RESOURCEGROUPNAME: trunck-base-mlops
  STORAGEACCOUNTNAME: ydmlopslake
  LOCATION: northeurope
  KEYVAULTNAME: kv-trunkbased-dev-131
  ENVPREFIX: dev
  MODELNAME: hate-pt-speech
  DESCRIPTION: 'A hate detection model for tweets in portuguese'
  CONDAENVNAME: transformers-torch-19