channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - azure-cli-core
  - mlflow-skinny
  - protobuf
  - pytorch
  - transformers
  - tensorboard
  - pandas
  - numpy
  - scikit-learn
  - statsmodels
  - pip:
      - azure-core
      - azureml-core
      - azureml-defaults
      - azureml-telemetry
      - azureml-mlflow      
      - inference-schema[numpy-support,pandas-support]
      - jobtools

