channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
      - azure-cli-core==2.33.1
      - azureml-core==1.39.0
      - azureml-defaults==1.39.0
      - azureml-telemetry==1.39.0
      - azureml-mlflow==1.39.0
      - mlflow-skinny==1.25.0.
      - protobuf~=3.19.0
      - torch==1.9
      - transformers==4.10
      - tensorboard==2.6
      - inference-schema[numpy-support,pandas-support]
      - pandas==1.3
      - numpy==1.19
      - scikit-learn==1.1.1
      - statsmodels==0.13.1
      - jobtools
