channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
      - azure-cli-core==2.33.1
      - azure-core==1.24.0
      - azureml-core
      - azureml-defaults
      - azureml-telemetry
      - azureml-mlflow
      - mlflow-skinny==1.25.0
      - protobuf~=3.19.0
      - torch==1.9
      - transformers==4.10
      - tensorboard==2.6
      - inference-schema[numpy-support,pandas-support]
      - pandas==1.3
      - numpy==1.19
      - scikit-learn==1.1.1
      - statsmodels==0.13.1
      - jobtools
      - ipykernel==6.4
      - jupyter==1.0
      - pytest==6.2.5
      - msrest==0.7.0
